// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/gofrs/uuid"
)

type SignInAttemptFilter struct {
	UserID *uuid.UUID `json:"userID"`
}

type UserFilter struct {
	Search string `json:"search"`
}
