// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateUserPayload struct {
	ID    *string `json:"id"`
	Item  *User   `json:"item"`
	Items []*User `json:"items"`
}

type DeleteUserPayload struct {
	ID  *string   `json:"id"`
	Ids []*string `json:"ids"`
}

type UpdateUserPayload struct {
	Item  *User   `json:"item"`
	Items []*User `json:"items"`
}
